### ISSUE TITLE
New Harbour contributions

### ISSUE THREAD

**Issue by mlacecilia** [rjopek/harbour-list#4]
Please, revise and add the recent contributions:

https://github.com/riztan/hbtelegram

https://github.com/EricLendvai/Harbour_ORM

https://github.com/hansmarc/Otis

https://github.com/APerricone/vscode-dbf

**Comment by Petewg** [comment]
Done. Thank you very much!
I don't like to be dogmatic, but I'm not sure about the inclusion of `<https://github.com/hansmarc/Otis>`, 
since it's just an executable of a closed-source-freeware, something which is not exactly compatible 
with this list nor (mainly) with the spirit of **Harbour-project** itself. 
In any case, any other opinion on this, (and creator's view, of course), would be quite interesting.

**Comment by mlacecilia** [comment]
Thanks Pete.
About Otis I agree, I asked you for revise, thus feel free to exclude it
from the list.
Sorry to be so poor in collaboration, but I'm just retiring and maybe I'll
have some time in near future.
Best regards.
--
Maurizio



Il ven 2 ott 2020, 09:53 Pete <notifications@github.com> ha scritto:
